config/routes.rb
Rails.application.routes.draw do
  resources :debts do
    resources :debt_payments
  end
  
  resources :loans do
    resources :loan_payments
  end

  resources :goals do
    resources :goal_progresses
  end

  resources :expenses #, only: [:index, :create, :new, :edit, :update, :destroy, :show]

  resources :budgets do
    resources :expenses
  end

  resources :incomes
  
  namespace :settings do
    resources :statuses
    resources :categories
    resources :income_sources
  end

  root "dashboard#index", as: 'dashboard'

  namespace :api do
    resources :budgets
  end

end

app/models/debt.rb
class Debt < ApplicationRecord
	include ActionView::Helpers::NumberHelper

	has_many :debt_payment
	belongs_to :status

	validates_presence_of :debtor_name, :amount, :due_date, :interest_rate, :status_id

	def formatted_due_date
    	due_date.strftime("%d %b, %Y")
	end

	def formatted_amount
		number_to_currency(amount, unit: "MK", separator: ".", delimiter: ",")
	end

	def formatted_interest_rate
		number_to_currency(interest_rate, unit: "MK", separator: ".", delimiter: ",")
	end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: %i[ show edit update destroy ]

  # GET /debts or /debts.json
  def index
    @debts = Debt.all
  end

  # GET /debts/1 or /debts/1.json
  def show
  end

  # GET /debts/new
  def new
    @debt = Debt.new
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts or /debts.json
  def create
    @debt = Debt.new(debt_params)

    respond_to do |format|
      if @debt.save
        format.html { redirect_to debt_url(@debt), notice: "Debt was successfully created." }
        format.json { render :show, status: :created, location: @debt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1 or /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to debt_url(@debt), notice: "Debt was successfully updated." }
        format.json { render :show, status: :ok, location: @debt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1 or /debts/1.json
  def destroy
    @debt.destroy

    respond_to do |format|
      format.html { redirect_to debts_url, notice: "Debt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def debt_params
      params.require(:debt).permit(:debtor_name, :amount, :due_date, :interest_rate, :notes, :status_id)
    end
end

app/views/debts/_debt.html.erb
<div class="card"  id="<%= dom_id debt %>">
    <div class="p-5 card-body">
      <div class="row">
          <div class="text-end col"><span class="badge bg-danger"><%= @debt.status.name%></span></div>
      </div>
      <div class="row">
          <div class="text-center col">
            <h2 class="mb-2">Debt from <%= @debt.debtor_name %></h2>
            <p class="text-muted mb-6">Debt #<%= @debt.id%></p>
          </div>
      </div>
      <div class="row">
          <div class="col-md-6 col-12">
           <h6 class="text-uppercase text-muted">
              Debtor name:
            </h6>
            <p class="mb-4">
              <%= debt.debtor_name %>
            </p>
            <h6 class="text-uppercase text-muted">
              Due date:
            </h6>
            <p class="mb-4">
              <%= debt.formatted_due_date %>
            </p>
          </div>
          
          <div class="text-md-end col-md-6 col-12">
            <h6 class="text-uppercase text-muted">
              Amount:
            </h6>
            <p class="mb-4">
              <%= debt.formatted_amount %>
            </p>
            <h6 class="text-uppercase text-muted">
              Interest rate:
            </h6>
            <p class="mb-4">
              <%= debt.formatted_interest_rate %>
            </p>
          </div>
          <div class="text-md-start col-12">
            <h6 class="text-uppercase text-muted">
              Notes:
            </h6>
            <p class="mb-4">
              <%= debt.notes || "N/A" %>
            </p>
          </div>
          <div class="text-md-end col-12">
            <%= link_to new_debt_debt_payment_url(debt), class: "btn-rounded-circle btn btn-primary"  do %>
              <i class="feather fe fe-plus"></i>
            <% end %>
          </div>
      </div>

      <div class="row">
          <div class="col-12">
            <div class="table-responsive">
                <table class="my-4 table">
                  <thead>
                      <tr>
                        <th class="px-0 bg-transparent border-top-0"><span class="h6">Amount</span></th>
                        <th class="px-0 bg-transparent border-top-0" colspan="2"><span class="h6">Payment Date</span></th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @debt.debt_payment.each do |debt_payment| %>
                      
                      <tr>
                        <td class="px-0">
                          <%= debt_payment.formatted_amount %>
                        </td>
                        <td class="px-0">
                          <%= debt_payment.formatted_repayment_date %>
                        </td>
                        <td class="text-end d-flex d-flex-end">
                          <%= button_to "Delete", @debt_payment, method: :delete, class: "btn btn-sm btn-danger pr-4"  %>
                          <%= link_to "Edit", debt_debt_payment_path(@debt, debt_payment), class: "btn btn-sm bt-primary" %>
                        </td>
                      </tr>
                    
                    <% end %>

                    <tr>
                      <td class="px-0 border-top border-top-2">
                        <strong>Total amount owed</strong>
                      </td>
                      <td colspan="2" class="px-0 text-end border-top border-top-2">
                        <span class="h3">
                          
                          <%= number_to_currency(@debt.debt_payment.sum(:amount), precision: 2, unit: "MK", separator: ".", delimiter: ",") %>

                        </span>
                      </td>
                    </tr>

                  </tbody>
                </table>
            </div>
          </div>
      </div>
    </div>
</div>

app/views/debts/_form.html.erb
<%= form_with(model: debt) do |form| %>
  <% if debt.errors.any? %>
    <div class="fade alert alert-light text-danger show">
      <div class="alert-heading h4">
        <%= pluralize(debt.errors.count, "error") %> prohibited this debt from being saved:
      </div>

      <ul>
        <% debt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :debtor_name, class: "form-label" %>
        <%= form.text_field :debtor_name, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :amount, class: "form-label" %>
        <%= form.number_field :amount, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-4 col-12">

      <div class="form-group">
        <%= form.label :due_date, class: "form-label" %>
        <%= form.date_field :due_date, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-4 col-12">

      <div class="form-group">
        <%= form.label :interest_rate, class: "form-label" %>
        <%= form.text_field :interest_rate, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-4 col-12">
      <div class="form-group">
        <%= form.label :status, class: "form-label" %>
        <%= form.select :status_id, options_for_select([['- Select from the list', nil]] + Status.all.map { |status| [status.name, status.id] }, (@debt.status_id.presence || nil)), {}, class: "form-control" %>
      </div>
    </div>
    
    <div class="col-12">
      <div class="form-group">
        <%= form.label :notes, class: "form-label"  %>
        <%= form.text_area :notes, class: "form-control", row: 8 %>
      </div>
    </div>

  </div>

  <hr class="mt-5 mb-5">
  <%= form.submit class: "w-100 btn btn-primary" %>
  <%= link_to "Back to debts", debts_path, class: "w-100 text-muted btn btn-link" %>

<% end %>

app/views/debts/edit.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">Editing Debt</h6>
                  <h1 class="header-title">Create Editing Debt</h1>
               </div>
            </div>
         </div>
      </div>

      <%= render "form", debt: @debt %>
   </div>
</div>

app/views/debts/index.html.erb
<div class="header">
    <div class="header-body">
      <div class="align-items-center row">
          <div class="col">
            <h6 class="header-pretitle">Overview</h6>
            <h1 class="header-title text-truncate"><%= 'Debts' %></h1>
          </div>
          <div class="col-auto">

            <%= link_to "New Debt", new_debt_path, type: "button", class: "btn btn-primary" %>

          </div>
      </div>
    </div>
</div>

<div class="card">
    <div class="table-responsive">
      <table class="card-table table-nowrap table table-sm">
          <thead>
            <tr>
                <th>Debt Name</th>
                <th>Amount</th>
                <th>Due Date</th>
                <th>Interest Rate</th>
                <th>Status</th>
                <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>

          <% @debts.each do |debt| %>
            <tr>
                <td><%= debt.debtor_name %></td>
                <td><%= debt.formatted_amount %></td>
                <td><%= debt.formatted_due_date %></td>
                <td><%= debt.formatted_interest_rate %></td>
                <td><span class="badge bg-success-soft"><%= debt.status.name %></span></td>
                <td>
                
                  <%= link_to "Show", debt %>

                </td>
            </tr>
          <% end %>

          </tbody>
      </table>
    </div>
</div>

app/views/debts/new.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">New debt</h6>
                  <h1 class="header-title">Create new debt</h1>
               </div>
            </div>
         </div>
      </div>

      <%= render "form", debt: @debt %>
   </div>
</div>

app/views/debts/show.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">Debt Details</h6>
                  <h1 class="header-title">Debt #<%= @debt.id %></h1>
               </div>
               <div class="col-auto d-flex">
                <%= link_to "Back to Debts", debts_path, type: "button", class: "lift btn btn-white" %>
                <%= link_to "Edit", edit_debt_path(@debt), type: "button", class: "lift mx-2 btn btn-primary" %>
                <%= button_to "Delete", @debt, method: :delete, class: "lift btn btn-danger" %>
              </div>
            </div>
         </div>
      </div>

      <%= render @debt %>

   </div>
</div>