config/routes.rb
Rails.application.routes.draw do
  resources :debts do
    resources :debt_payments
  end
  
  resources :loans do
    resources :loan_payments
  end

  resources :goals do
    resources :goal_progresses
  end

  resources :expenses #, only: [:index, :create, :new, :edit, :update, :destroy, :show]

  resources :budgets do
    resources :expenses
  end

  resources :incomes
  
  namespace :settings do
    resources :statuses
    resources :categories
    resources :income_sources
  end

  root "dashboard#index", as: 'dashboard'

  namespace :api do
    resources :budgets
  end

end

app/models/loan.rb
class Loan < ApplicationRecord
	include ActionView::Helpers::DateHelper
	include ActionView::Helpers::NumberHelper

	has_many :loan_payment
	belongs_to :status
	
	validates_presence_of :lender, :amount, :interest_rate, :start_date, :end_date, :status_id

	def formatted_start_date
    	start_date.strftime("%d %b, %Y")
	end

	def formatted_end_date
    	end_date.strftime("%d %b, %Y")
	end

	def duration
		distance_of_time_in_words(start_date, end_date, include_seconds: true)
	end

	def formatted_amount
		number_to_currency(amount, unit: "MK", separator: ".", delimiter: ",")
	end

	def formatted_interest_rate
		number_to_currency(interest_rate, unit: "MK", separator: ".", delimiter: ",")
	end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show
      @loan = Loan.includes(:loan_payment).find(params[:id])
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to loan_url(@loan), notice: "Loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to loan_url(@loan), notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:lender, :amount, :interest_rate, :start_date, :end_date, :status_id)
    end
end

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
    <% if loan.errors.any? %>
    <div class="fade alert alert-light text-danger show">
      <div class="alert-heading h4">
        <%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:
      </div>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :lender, class: "form-label" %>
        <%= form.text_field :lender, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :amount, class: "form-label" %>
        <%= form.number_field :amount, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :start_date, class: "form-label" %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :end_date, class: "form-label" %>
        <%= form.date_field :end_date, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :interest_rate, class: "form-label" %>
        <%= form.text_field :interest_rate, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-6 col-12">
      <div class="form-group">
        <%= form.label :status, class: "form-label" %>
        <%= form.select :status_id, options_for_select([['- Select from the list', nil]] + Status.all.map { |status| [status.name, status.id] }, (@loan.status_id.presence || nil)), {}, class: "form-control" %>
      </div>
    </div>
    
  </div>

  <hr class="mt-5 mb-5">
  <%= form.submit class: "w-100 btn btn-primary" %>
  <%= link_to "Back to loans", loans_path, class: "w-100 text-muted btn btn-link" %>

<% end %>

app/views/loans/_loan.html.erb
<div class="card"  id="<%= dom_id loan %>">
    <div class="p-5 card-body">
      <div class="row">
          <div class="text-end col"><span class="badge bg-danger"><%= @loan.status.name%></span></div>
      </div>
      <div class="row">
          <div class="text-center col">
            <h2 class="mb-2">Loan form <%= @loan.lender %></h2>
            <p class="text-muted mb-6">Loan #<%= @loan.id%></p>
          </div>
      </div>
      <div class="row">
          <div class="col-md-6 col-12">
           <h6 class="text-uppercase text-muted">
              Lender:
            </h6>
            <p class="mb-4">
              <%= loan.lender %>
            </p>
            <h6 class="text-uppercase text-muted">
              Amount:
            </h6>
            <p class="mb-4">
              <%= loan.formatted_amount %>
            </p>
            <h6 class="text-uppercase text-muted">
              Interest rate:
            </h6>
            <p class="mb-4">
              <%= loan.formatted_interest_rate %>
            </p>
          </div>
          
          <div class="text-md-end col-md-6 col-12">
            <h6 class="text-uppercase text-muted">
              Start date:
            </h6>
            <p class="mb-4">
              <%= loan.formatted_start_date %>
            </p>
            <h6 class="text-uppercase text-muted">
              End date:
            </h6>
            <p class="mb-4">
              <%= loan.formatted_end_date %>
            </p>
          </div>
      </div>
      <div class="row">
          <div class="col-12">
            <div class="table-responsive">
                <table class="my-4 table">
                  <thead>
                      <tr>
                        <th class="px-0 bg-transparent border-top-0"><span class="h6">Amount</span></th>
                        <th class="px-0 bg-transparent border-top-0" colspan="2"><span class="h6">Payment Date</span></th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @loan.loan_payment.each do |loan_payment| %>
                      
                      <tr>
                        <td class="px-0">
                          <%= loan_payment.formatted_amount %>
                        </td>
                        <td class="px-0">
                          <%= loan_payment.formatted_payment_date %>
                        </td>
                        <td class="text-end d-flex d-flex-end">
                          <%= button_to "Delete", @loan_payment, method: :delete, class: "btn btn-sm btn-danger pr-4"  %>
                          <%= link_to "Edit", edit_loan_loan_payment_path(@loan, loan_payment), class: "btn btn-sm bt-primary" %>
                        </td>
                      </tr>
                    
                    <% end %>

                    <tr>
                      <td class="px-0 border-top border-top-2">
                        <strong>Total amount paid</strong>
                      </td>
                      <td colspan="2" class="px-0 text-end border-top border-top-2">
                        <span class="h3">
                          
                          <%= number_to_currency(@loan.loan_payment.sum(:amount), precision: 2, unit: "MK", separator: ".", delimiter: ",") %>

                        </span>
                      </td>
                    </tr>

                  </tbody>
                </table>
            </div>
          </div>
      </div>
    </div>
</div>

app/views/loans/edit.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">Editing loan</h6>
                  <h1 class="header-title">Create Editing loan</h1>
               </div>
            </div>
         </div>
      </div>

      <%= render "form", loan: @loan %>
   </div>
</div>

app/views/loans/index.html.erb
<div class="header">
    <div class="header-body">
      <div class="align-items-center row">
          <div class="col">
            <h6 class="header-pretitle">Overview</h6>
            <h1 class="header-title text-truncate"><%= 'Loans' %></h1>
          </div>
          <div class="col-auto">

            <%= link_to "New Loan", new_loan_path, type: "button", class: "btn btn-primary" %>

          </div>
      </div>
    </div>
</div>

<% if notice %>
<div role="alert" class="fade alert alert-danger show">
  <%= notice %>
</div>
<% end %>

<div class="card">
    <div class="table-responsive">
      <table class="card-table table-nowrap table table-sm">
          <thead>
            <tr>
                <th>Lender</th>
                <th>Amount</th>
                <th>Interest Rate</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Duration</th>
                <th>Status</th>
                <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>

          <% @loans.each do |loan| %>
            <tr>
                <td><%= loan.lender %></td>
                <td><%= loan.formatted_amount %></td>
                <td><%= loan.formatted_interest_rate %></td>
                <td><%= loan.formatted_start_date %></td>
                <td><%= loan.formatted_end_date %></td>
                <td><%= loan.duration %></td>
                <td><span class="badge bg-<%= loan.status.color %>-soft"><%= loan.status.name %></span></td>
                <td class="text-end">
                  <%= link_to loan_path(loan), type: "button", class: "btn-rounded-circle btn btn-white btn-sm", title: "Show details" do %>
                    <i class="fe fe-eye"></i>
                  <% end %>

                  <%= link_to new_loan_loan_payment_path(loan), type: "button", class: "btn-rounded-circle btn btn-sm btn-primary", title: "Pay back loan" do %>
                    <i class="fe fe-check"></i>
                  <% end %>

                </td>
            </tr>
          <% end %>

          </tbody>
      </table>
    </div>
</div>

app/views/loans/new.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">New loan</h6>
                  <h1 class="header-title">Create new loan</h1>
               </div>
            </div>
         </div>
      </div>

      <%= render "form", loan: @loan %>
   </div>
</div>

app/views/loans/show.html.erb
<div class="justify-content-center row">
   <div class="col-xl-8 col-lg-10 col-12">
      <div class="header mt-md-5">
         <div class="header-body">
            <div class="align-items-center row">
               <div class="col">
                  <h6 class="header-pretitle">Loan Details</h6>
                  <h1 class="header-title">Loan #<%= @loan.id %></h1>
               </div>
               <div class="col-auto d-flex">
                <%= link_to "Back to Loans", loans_path, type: "button", class: "lift btn btn-white" %>
                <%= link_to "Edit", edit_loan_path(@loan), type: "button", class: "lift mx-2 btn btn-primary" %>
                <%= button_to "Delete", @loan, method: :delete, class: "lift btn btn-danger" %>
              </div>
            </div>
         </div>
      </div>

      <%= render @loan %>

   </div>
</div>