config/routes.rb
Rails.application.routes.draw do
  resources :debts do
    resources :debt_payments
  end
  
  resources :loans do
    resources :loan_payments
  end

  resources :goals do
    resources :goal_progresses
  end

  resources :expenses #, only: [:index, :create, :new, :edit, :update, :destroy, :show]

  resources :budgets do
    resources :expenses
  end

  resources :incomes
  
  namespace :settings do
    resources :statuses
    resources :categories
    resources :income_sources
  end

  root "dashboard#index", as: 'dashboard'

  namespace :api do
    resources :budgets
  end

end

app/controllers/goal_progresses_controller.rb
class GoalProgressesController < ApplicationController
  before_action :set_goal_progress, only: %i[ show edit update destroy ]

  # GET /goal_progresses or /goal_progresses.json
  def index
    @goal_progresses = GoalProgress.all
  end

  # GET /goal_progresses/1 or /goal_progresses/1.json
  def show
  end

  # GET /goal_progresses/new
  def new
    @goal_progress = GoalProgress.new
  end

  # GET /goal_progresses/1/edit
  def edit
  end

  # POST /goal_progresses or /goal_progresses.json
  def create
    @goal_progress = GoalProgress.new(goal_progress_params)

    respond_to do |format|
      if @goal_progress.save
        format.html { redirect_to goal_progress_url(@goal_progress), notice: "Goal progress was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_progresses/1 or /goal_progresses/1.json
  def update
    respond_to do |format|
      if @goal_progress.update(goal_progress_params)
        format.html { redirect_to goal_progress_url(@goal_progress), notice: "Goal progress was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_progresses/1 or /goal_progresses/1.json
  def destroy
    @goal_progress.destroy

    respond_to do |format|
      format.html { redirect_to goal_progresses_url, notice: "Goal progress was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_progress
      @goal_progress = GoalProgress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_progress_params
      params.require(:goal_progress).permit(:goals_id, :amount_saved, :completion_percentage, :statuses_id, :date)
    end
end

app/views/goal_progresses/_form.html.erb
<%= form_with(model: goal_progress, url: goal_goal_progresses_path(goal)) do |form| %>

    <% if goal_progress.errors.any? %>
    <div class="fade alert alert-light text-danger show">
      <div class="alert-heading h4">
        <%= pluralize(goal_progress.errors.count, "error") %> prohibited this goal progess from being saved:
      </div>

      <ul>
        <% goal_progress.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">

  <div>

    <%= form.hidden_field :goal_id, value: @goal.id %>
  
  </div>

  <div class="col-6">

    <div class="form-group">
      <%= form.label :amount_saved, class: "form-label" %>
      <%= form.number_field :amount_saved, class: "form-control" %>
    </div>

  </div>

    <div class="col-md-6 col-12">

      <div class="form-group">
        <%= form.label :completion_percentage, class: "form-label" %>
        <%= form.text_field :completion_percentage, class: "form-control" %>
      </div>

    </div>

    <div class="col-md-4 col-12">
      <div class="form-group">
        <%= form.label :status, class: "form-label" %>
        <%= form.select :status_id, options_for_select([['- Select from the list', nil]] + Status.all.map { |status| [status.name, status.id] }, (@goal_progress.status_id.presence || nil)), {}, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">

      <div class="form-group">
        <%= form.label :date, class: "form-label" %>
        <%= form.date_field :date, class: "form-control" %>
      </div>

    </div>
</div>

  <hr class="mt-5 mb-5">
  <%= form.submit class: "w-100 btn btn-primary" %>
  <%= link_to "Back to goals", goals_path, class: "w-100 text-muted btn btn-link" %>

<% end %>

app/views/goal_progresses/_goal_progress.html.erb
<div id="<%= dom_id goal_progress %>">
  <p>
    <strong>Goals:</strong>
    <%= goal_progress.goals_id %>
  </p>

  <p>
    <strong>Amount saved:</strong>
    <%= goal_progress.amount_saved %>
  </p>

  <p>
    <strong>Completion percentage:</strong>
    <%= goal_progress.completion_percentage %>
  </p>

  <p>
    <strong>Statuses:</strong>
    <%= goal_progress.statuses_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= goal_progress.date %>
  </p>

</div>

app/views/goal_progresses/edit.html.erb
<h1>Editing goal progress</h1>

<%= render "form", goal_progress: @goal_progress %>

<br>

<div>
  <%= link_to "Show this goal progress", @goal_progress %> |
  <%= link_to "Back to goal progresses", goal_progresses_path %>
</div>

app/views/goal_progresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Goal progresses</h1>

<div id="goal_progresses">
  <% @goal_progresses.each do |goal_progress| %>
    <%= render goal_progress %>
    <p>
      <%= link_to "Show this goal progress", goal_progress %>
    </p>
  <% end %>
</div>

<%= link_to "New goal progress", new_goal_progress_path %>

app/views/goal_progresses/new.html.erb
<h1>New goal progress</h1>

<%= render "form", goal_progress: @goal_progress %>

<br>

<div>
  <%= link_to "Back to goal progresses", goal_progresses_path %>
</div>

app/views/goal_progresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @goal_progress %>

<div>
  <%= link_to "Edit this goal progress", edit_goal_progress_path(@goal_progress) %> |
  <%= link_to "Back to goal progresses", goal_progresses_path %>

  <%= button_to "Destroy this goal progress", @goal_progress, method: :delete %>
</div>